name: E2E test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      run_tests:
        description: 'Run E2E tests'
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        node: [20]  # Updated to match Cypress requirements

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Changed from 18 to 20

      - name: Install dependencies
        run: npm install

      - name: Fix ESLint error (temporary)
        run: |
          # Fix the unescaped apostrophe issue
          sed -i "s/'/&apos;/g" ./app/page.js || echo "ESLint fix attempted"

      - name: Build application
        run: npm run build
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-app
          path: |
            .next/
            node_modules/
            package*.json

  test:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.run_tests == 'true' || github.event_name != 'workflow_dispatch'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: built-app
          
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Changed from 18 to 20

      - name: Install Cypress dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      - name: Test run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/*.cy.js
          install: false  # Since we already installed dependencies